---
name: Uptime Kuma Woz Edition
version: 1.0.0
slug: uptime-kuma-woz
description: It is a self-hosted monitoring tool like "Uptime Robot"
url: https://github.com/woznet/WozDev-HA-Addons
webui: http://[HOST]:[PORT:3001]
init: false
arch:
  - aarch64
  - amd64
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
discovery:
  - uptime_kuma
